[package]
name = "rusty-ponyo"
version = "0.1.1"
authors = ["kawaemon <34652535+kawaemon@users.noreply.github.com>"]
edition = "2018"

[features]
discord_client = ["serenity"]
console_client = []

mongo_db = ["mongodb"]
memory_db = []

dev = ["memory_db", "console_client"]
prod = ["mongo_db", "discord_client"]

default = ["dev"]


[dependencies]
anyhow = "1.0"
async-trait = "0.1"
dotenv = "0.15"
serde = { version = "1.0", features = ["derive"] }
tokio-stream = "0.1"
tracing = "0.1"
tracing-subscriber = "0.2"
chrono = { version = "0.4", features = ["serde"] }
parking_lot = "0.11"
cfg-if = "1.0"
serde_json = "1.0"
chrono-tz = "0.5"
hashbrown = "0.9"
once_cell = "1.7"

[dependencies.serenity]
version = "0.10"
optional = true
default-features = false
features = ["rustls_backend", "client", "gateway", "model", "cache"]

[dependencies.tokio]
version = "1.2"
features = ["rt-multi-thread", "parking_lot", "fs"]

[dependencies.mongodb]
version = "2.0.0-alpha"
optional = true

[profile.release]
lto = true
codegen-units = 1
