[package]
name = "message-alias-bot"
version = "0.1.0"
authors = ["kawaemon <34652535+kawaemon@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
async-trait = "0.1.42"
dotenv = "0.15.0"
mongodb = "1.1.1"
serde = "1.0.119"
serenity = "0.10.2"
tokio = "0.2"
tracing = "0.1.22"
tracing-subscriber = "0.2.15"
